# -*- coding: utf-8 -*-
"""expensetracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUW3sbSaL2If7dorYLkFRGFCsbi2sIUU
"""

file_name = "expenses.txt"


def add_expense():
    try:
        category = input("Enter category (Food/Travel/Shopping): ")
        amount = float(input("Enter amount: "))

        with open(file_name, "a") as f:
            f.write(f"{category},{amount}\n")

        print("Expense added successfully!")

    except ValueError:
        print("Invalid amount! Please enter a number.")


def view_expenses():
    try:
        with open(file_name, "r") as f:
            data = f.readlines()

            if not data:
                print("No expenses recorded yet.")
                return

            print("\n--- Expense List ---")
            for line in data:
                category, amount = line.strip().split(",")
                print(f"Category: {category} | Amount: {amount}/-")

    except FileNotFoundError:
        print("No expense file found! Add expenses first.")


def calculate_total():
    total = 0

    try:
        with open(file_name, "r") as f:
            for line in f:
                _, amount = line.strip().split(",")
                total += float(amount)

        print(f"\nTotal Expense: {total}/-")

    except FileNotFoundError:
        print("No expense file found! Add expenses first.")


# EXTRA FEATURE (kept but not in menu)
def category_count():
    counts = {}

    try:
        with open(file_name, "r") as f:
            for line in f:
                category, _ = line.strip().split(",")

                if category in counts:
                    counts[category] += 1
                else:
                    counts[category] = 1

        print("\nCategory-wise Count:")
        for cat, count in counts.items():
            print(f"{cat}: {count}")

    except FileNotFoundError:
        print("No expense file found! Add expenses first.")


def main():
    while True:
        print("\n==== Expense Tracker ====")
        print("1. Add Expense")
        print("2. View Expenses")
        print("3. Total Expense")
        print("4. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            add_expense()
        elif choice == "2":
            view_expenses()
        elif choice == "3":
            calculate_total()
        elif choice == "4":
            print("Exiting... Bye!")
            break
        else:
            print("Invalid choice! Try again.")


main()

